# Generated by Django 2.0.1 on 2018-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(max_length=5)),
                ('item', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('paytype', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
