# Generated by Django 2.0.1 on 2018-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0003_auto_20180130_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='paytype',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
